In [2]:
import numpy as np

list_ = [ 1,2 , 3 , 4 , 5 ]

array_list = np.array(object = list_)

In [3]:
array_list

array([1, 2, 3, 4, 5])

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

ANS:- yes their is a difference between the list and array.
list consume more memory as compare to array.both are of different datatypes

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [8]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [9]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and array_list.

In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [13]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [14]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [15]:
num_array.shape

(2, 3)

In [16]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
import numpy as np
a=np.zeros((3,3))

In [19]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.matrix(a)

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [46]:
np.diag((1,1,1,1,1))

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])